### ISSUE TITLE
SSL keys verify error.

### ISSUE THREAD

**Issue by myhirra** [zxlie/website-ssl.sh#1]
nginx: [emerg] SSL_CTX_use_PrivateKey_file("/home/work/www/ssl/domain.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)

**Comment by myhirra** [comment]
`$ sh webstite-ssl.sh pem`

```
Traceback(most recent call last)
    File "acme_tiny.py" , line 2, in <module>
     ....
ImportError: No module named argparse
```

如果你碰到了类似的错误，请安装argparse模块。

```
$ yum install easy_install
$ easy_install argparse
```

**Comment by myhirra** [comment]
```
Traceback (most recent call last):
server {
  File "acme_tiny.py", line 198, in <module>
    main(sys.argv[1:])
  File "acme_tiny.py", line 194, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca)
  File "acme_tiny.py", line 123, in get_crt
    wellknown_path, wellknown_url))
ValueError: Wrote file to /home/work/www/challenges/JbSpPOserver {
Mo8CXFzJJFSwPI5kIEk9WSdHmY5Ej13-zmOUg, but couldn't download http://hirra.cn/.well-known/acme-challenge/JbSpPOMo8CXFzJJFSwPI5kIEk9WSdHmY5Ej13-zmOUg
```

如果你碰到了类似的错误，那是因为没有在nignx里加上

```
 location ^~ /.well-known/acme-challenge/ {
        alias /home/work/www/challenges/;
        try_files  $uri =404;
    }
```

一定要先加上这个，nginx reload后，再 安装ssl-encrypt.pem文件

**Comment by myhirra** [comment]
一切ready后，如果此时nginx reload，出现 类似 『Server Refused』的提示。这时候可以尝试杀掉nginx进程，然后再次启动nginx
